<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * ==========================================================================
 * INFRASTRUCTURE MODEL
 * ==========================================================================
 *
 * AuditLog Model
 * ==========================================================================
 *
 * Represents one immutable audit record generated by the platform.
 *
 * Audit logs provide complete traceability of important business
 * operations for security, compliance and troubleshooting.
 *
 * Audit records are NEVER modified or deleted.
 *
 * --------------------------------------------------------------------------
 * Responsibilities
 * --------------------------------------------------------------------------
 * • Record business events.
 * • Record administrator actions.
 * • Record system actions.
 * • Store previous values.
 * • Store new values.
 * • Store execution context.
 * • Preserve immutable history.
 *
 * --------------------------------------------------------------------------
 * Business Rules
 * --------------------------------------------------------------------------
 * BR-48 Every important action is audited.
 * BR-49 Audit history is immutable.
 * BR-50 Store actor, action, entity and changes.
 * BR-51 Store IP address and browser.
 * BR-55 Administrator changes are audited.
 *
 * --------------------------------------------------------------------------
 * Module
 * --------------------------------------------------------------------------
 * Infrastructure
 * ==========================================================================
 */

class AuditLog extends Model
{
    use HasFactory;

    /*-------------------------------------------------------------------------
    | Mass Assignment
    |------------------------------------------------------------------------*/

    protected $fillable = [

        'user_id',

        'request_id',

        'action',

        'entity_type',

        'entity_id',

        'old_values',

        'new_values',

        'ip_address',

        'user_agent',

    ];

    /*-------------------------------------------------------------------------
    | Attribute Casting
    |------------------------------------------------------------------------*/

    protected function casts(): array
    {
        return [

            'old_values' => 'array',

            'new_values' => 'array',

            'created_at' => 'datetime',

            'updated_at' => 'datetime',

        ];
    }

    /*-------------------------------------------------------------------------
    | Organization Relationships
    |------------------------------------------------------------------------*/

    /**
     * User responsible for the action.
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    /*-------------------------------------------------------------------------
    | Runtime Relationships
    |------------------------------------------------------------------------*/

    /**
     * Related request (optional).
     */
    public function request(): BelongsTo
    {
        return $this->belongsTo(Request::class);
    }

    /*-------------------------------------------------------------------------
    | Query Scopes
    |------------------------------------------------------------------------*/

    /**
     * Filter by action.
     */
    public function scopeAction(Builder $query, string $action): Builder
    {
        return $query->where('action', $action);
    }

    /**
     * Filter by entity.
     */
    public function scopeEntity(Builder $query, string $entity): Builder
    {
        return $query->where('entity_type', $entity);
    }

    /**
     * Filter by user.
     */
    public function scopeByUser(Builder $query, int $userId): Builder
    {
        return $query->where('user_id', $userId);
    }

    /*-------------------------------------------------------------------------
    | Helper Methods
    |------------------------------------------------------------------------*/

    /**
     * Determine whether this action modified data.
     *
     * NOTE (Etape 4) : renommee depuis hasChanges() - ce nom entrait en
     * collision avec Illuminate\Database\Eloquent\Model::hasChanges(),
     * deja definie par Eloquent avec une signature differente, ce qui
     * provoquait une erreur fatale PHP a la premiere instanciation
     * reelle d'un AuditLog.
     */
    public function hasDataChanges(): bool
    {
        return !empty($this->old_values) || !empty($this->new_values);
    }

    /**
     * Determine whether this action is linked to a Request.
     */
    public function belongsToRequest(): bool
    {
        return !is_null($this->request_id);
    }

    /**
     * Return a human-readable entity reference.
     */
    public function entityReference(): string
    {
        return "{$this->entity_type} #{$this->entity_id}";
    }
}