<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * ==========================================================================
 * INFRASTRUCTURE MODEL
 * ==========================================================================
 *
 * AuditLog Model
 * ==========================================================================
 *
 * Represents one immutable audit record generated by the platform.
 *
 * Audit logs provide complete traceability of important business
 * operations for security, compliance and troubleshooting.
 *
 * Audit records are NEVER modified or deleted.
 *
 * --------------------------------------------------------------------------
 * Responsibilities
 * --------------------------------------------------------------------------
 * • Record business events.
 * • Record administrator actions.
 * • Record system actions.
 * • Store previous values.
 * • Store new values.
 * • Store execution context.
 * • Preserve immutable history.
 *
 * --------------------------------------------------------------------------
 * Business Rules
 * --------------------------------------------------------------------------
 * BR-48 Every important action is audited.
 * BR-49 Audit history is immutable.
 * BR-50 Store actor, action, entity and changes.
 * BR-51 Store IP address and browser.
 * BR-55 Administrator changes are audited.
 *
 * --------------------------------------------------------------------------
 * Module
 * --------------------------------------------------------------------------
 * Infrastructure
 * ==========================================================================
 */

class AuditLog extends Model
{
    use HasFactory;

    /*-------------------------------------------------------------------------
    | Mass Assignment
    |------------------------------------------------------------------------*/

    protected $fillable = [

        'user_id',

        'request_id',

        'action',

        'entity_type',

        'entity_id',

        'old_values',

        'new_values',

        'ip_address',

        'user_agent',

    ];

    /*-------------------------------------------------------------------------
    | Attribute Casting
    |------------------------------------------------------------------------*/

    protected function casts(): array
    {
        return [

            'old_values' => 'array',

            'new_values' => 'array',

            'created_at' => 'datetime',

            'updated_at' => 'datetime',

        ];
    }

    /*-------------------------------------------------------------------------
    | Organization Relationships
    |------------------------------------------------------------------------*/

    /**
     * User responsible for the action.
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    /*-------------------------------------------------------------------------
    | Runtime Relationships
    |------------------------------------------------------------------------*/

    /**
     * Related request (optional).
     */
    public function request(): BelongsTo
    {
        return $this->belongsTo(Request::class);
    }

    /*-------------------------------------------------------------------------
    | Query Scopes
    |------------------------------------------------------------------------*/

    /**
     * Filter by action.
     */
    public function scopeAction(Builder $query, string $action): Builder
    {
        return $query->where('action', $action);
    }

    /**
     * Filter by entity.
     */
    public function scopeEntity(Builder $query, string $entity): Builder
    {
        return $query->where('entity_type', $entity);
    }

    /**
     * Filter by user.
     */
    public function scopeByUser(Builder $query, int $userId): Builder
    {
        return $query->where('user_id', $userId);
    }

    /*-------------------------------------------------------------------------
    | Helper Methods
    |------------------------------------------------------------------------*/

    /**
     * Determine whether this action modified data.
     *
     * NOTE: renommee depuis hasChanges() - ce nom entrait en
     * collision avec Illuminate\Database\Eloquent\Model::hasChanges(),
     * deja definie par Eloquent avec une signature differente, ce qui
     * provoquait une erreur fatale PHP a la première instanciation
     * réelle d'un AuditLog.
     */
    public function hasDataChanges(): bool
    {
        return !empty($this->old_values) || !empty($this->new_values);
    }

    /**
     * Determine whether this action is linked to a Request.
     */
    public function belongsToRequest(): bool
    {
        return !is_null($this->request_id);
    }

    /**
     * Return a human-readable entity référence.
     */
    public function entityReference(): string
    {
        return "{$this->entity_type} #{$this->entity_id}";
    }

    /**
     * Lien réel vers l'entité concernée, quand on en a un - notamment
     * "Request" qui doit renvoyer vers la Demande elle-même (voir
     * my-requests.show, consultable par un Administrateur grâce au
     * before() de RequestPolicy) plutôt que de n'afficher qu'un texte
     * "Request #3" sans rien à cliquer.
     */
    public function entityUrl(): ?string
    {
        return match ($this->entity_type) {
            'Request' => route('workflow.my-requests.show', $this->entity_id),
            'Form' => route('workflow.admin.forms.edit', $this->entity_id),
            'Workflow' => route('workflow.admin.workflows.edit', $this->entity_id),
            'User' => route('organisation.users.edit', $this->entity_id),
            'Department' => route('organisation.departments.edit', $this->entity_id),
            'Entity' => route('organisation.entities.edit', $this->entity_id),
            default => null,
        };
    }

    /**
     * Libellé français lisible pour l'écran Historique - une seule
     * source de vérité plutôt que de dupliquer cette table de
     * correspondance dans la vue. Les codes d'action inconnus (ex. un
     * nouveau type ajouté plus tard sans mettre à jour cette liste)
     * s'affichent tels quels plutôt que de faire échouer l'écran.
     */
    public function actionLabel(): string
    {
        return match ($this->action) {
            'user_registered' => 'Inscription',
            'user_created' => 'Utilisateur créé',
            'user_updated' => 'Utilisateur modifié',
            'user_profile_updated' => 'Profil modifié',
            'user_deactivated' => 'Utilisateur désactivé',
            'user_activated' => 'Utilisateur réactivé',
            'active_role_switched' => 'Changement de rôle actif',
            'department_created' => 'Département créé',
            'department_updated' => 'Département modifié',
            'department_archived' => 'Département archivé',
            'department_restored' => 'Département réactivé',
            'entity_created' => 'Entité créée',
            'entity_updated' => 'Entité modifiée',
            'entity_archived' => 'Entité archivée',
            'entity_restored' => 'Entité réactivée',
            'business_function_created' => 'Fonction métier créée',
            'business_function_updated' => 'Fonction métier modifiée',
            'business_function_archived' => 'Fonction métier archivée',
            'business_function_restored' => 'Fonction métier réactivée',
            'form_category_created' => 'Catégorie de formulaire créée',
            'form_category_updated' => 'Catégorie de formulaire modifiée',
            'form_category_archived' => 'Catégorie de formulaire archivée',
            'form_category_restored' => 'Catégorie de formulaire réactivée',
            'workflow_category_created' => 'Catégorie de workflow créée',
            'workflow_category_updated' => 'Catégorie de workflow modifiée',
            'workflow_category_archived' => 'Catégorie de workflow archivée',
            'workflow_category_restored' => 'Catégorie de workflow réactivée',
            'form_created' => 'Formulaire créé',
            'form_updated' => 'Formulaire modifié',
            'form_published' => 'Formulaire publié',
            'form_archived' => 'Formulaire archivé',
            'form_duplicated' => 'Formulaire dupliqué',
            'form_priority_updated' => 'Urgence du formulaire modifiée',
            'form_field_created' => 'Champ ajouté',
            'form_field_updated' => 'Champ modifié',
            'form_field_deleted' => 'Champ supprimé',
            'field_option_created' => 'Option ajoutée',
            'field_option_deleted' => 'Option supprimée',
            'field_option_set_default' => 'Option définie par défaut',
            'workflow_created' => 'Workflow créé',
            'workflow_updated' => 'Workflow modifié',
            'workflow_published' => 'Workflow publié',
            'workflow_archived' => 'Workflow archivé',
            'workflow_duplicated' => 'Workflow dupliqué',
            'workflow_step_created' => 'Étape ajoutée',
            'workflow_step_updated' => 'Étape modifiée',
            'workflow_step_deleted' => 'Étape supprimée',
            'workflow_start_step_changed' => "Étape de début modifiée",
            'workflow_transition_created' => 'Transition ajoutée',
            'workflow_transition_updated' => 'Transition modifiée',
            'workflow_transition_deleted' => 'Transition supprimée',
            'transition_condition_created' => 'Condition ajoutée',
            'transition_condition_deleted' => 'Condition supprimée',
            'request_submitted' => 'Demande soumise',
            'request_approved' => 'Demande approuvée',
            'request_rejected' => 'Demande rejetée',
            'workflow_finished' => 'Demande clôturée',
            default => $this->action,
        };
    }

    /**
     * Regroupement visuel par nature de l'action (créer/modifier/
     * archiver-supprimer/publier) pour l'écran Historique - dérivé du
     * suffixe du code plutôt que d'une seconde table de correspondance
     * à tenir à jour en double.
     */
    public function actionTone(): string
    {
        return match (true) {
            str_ends_with($this->action, '_created'), $this->action === 'user_registered' => 'success',
            str_ends_with($this->action, '_deleted'),
            str_ends_with($this->action, '_archived'),
            str_ends_with($this->action, '_deactivated'),
            $this->action === 'request_rejected' => 'danger',
            str_ends_with($this->action, '_published'),
            str_ends_with($this->action, '_restored'),
            str_ends_with($this->action, '_activated'),
            $this->action === 'request_approved',
            $this->action === 'workflow_finished' => 'blue',
            default => 'slate',
        };
    }
}