<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * ==========================================================================
 * INFRASTRUCTURE MODEL
 * ==========================================================================
 *
 * Notification Model
 * ==========================================================================
 *
 * Represents one notification generated by the platform.
 *
 * Notifications are created automatically by the Workflow Engine
 * whenever an event requires informing a User.
 *
 * This model stores notification metadata only.
 * Delivery is handled later by NotificationService.
 *
 * --------------------------------------------------------------------------
 * Responsibilities
 * --------------------------------------------------------------------------
 * • Belongs to one Request.
 * • Targets one User.
 * • Supports Email notifications.
 * • Supports In-App notifications.
 * • Supports reminders.
 * • Supports escalation.
 * • Records delivery status.
 *
 * --------------------------------------------------------------------------
 * Business Rules
 * --------------------------------------------------------------------------
 * BR-43 Notifications are generated automatically.
 * BR-44 Email and In-App supported.
 * BR-45 Reminder notifications.
 * BR-46 Escalation after timeout.
 * BR-47 Delivery failures logged.
 *
 * --------------------------------------------------------------------------
 * Module
 * --------------------------------------------------------------------------
 * Infrastructure
 * ==========================================================================
 */

class Notification extends Model
{
    use HasFactory;

    /*-------------------------------------------------------------------------
    | Status Constants
    |------------------------------------------------------------------------*/

    public const PENDING = 'Pending';

    public const SENT = 'Sent';

    public const FAILED = 'Failed';

    public const READ = 'Read';

    /*-------------------------------------------------------------------------
    | Mass Assignment
    |------------------------------------------------------------------------*/

    protected $fillable = [

        'request_id',

        'recipient_id',

        'title',

        'message',

        'channel',

        'status',

        'sent_at',

        'read_at',

        'failure_reason',

    ];

    /*-------------------------------------------------------------------------
    | Attribute Casting
    |------------------------------------------------------------------------*/

    protected function casts(): array
    {
        return [

            'sent_at' => 'datetime',

            'read_at' => 'datetime',

            'created_at' => 'datetime',

            'updated_at' => 'datetime',

        ];
    }

    /*-------------------------------------------------------------------------
    | Runtime Relationships
    |------------------------------------------------------------------------*/

    /**
     * Related Request.
     */
    public function request(): BelongsTo
    {
        return $this->belongsTo(Request::class);
    }

    /*-------------------------------------------------------------------------
    | Organization Relationships
    |------------------------------------------------------------------------*/

    /**
     * User receiving the notification.
     */
    public function recipient(): BelongsTo
    {
        return $this->belongsTo(User::class, 'recipient_id');
    }

    /*-------------------------------------------------------------------------
    | Query Scopes
    |------------------------------------------------------------------------*/

    /**
     * Pending notifications.
     */
    public function scopePending(Builder $query): Builder
    {
        return $query->where('status', self::PENDING);
    }

    /**
     * Successfully sent notifications.
     */
    public function scopeSent(Builder $query): Builder
    {
        return $query->where('status', self::SENT);
    }

    /**
     * Failed notifications.
     */
    public function scopeFailed(Builder $query): Builder
    {
        return $query->where('status', self::FAILED);
    }

    /**
     * Read notifications.
     */
    public function scopeRead(Builder $query): Builder
    {
        return $query->where('status', self::READ);
    }

    /*-------------------------------------------------------------------------
    | Helper Methods
    |------------------------------------------------------------------------*/

    /**
     * Determine whether notification was sent.
     */
    public function isSent(): bool
    {
        return $this->status === self::SENT;
    }

    /**
     * Determine whether notification failed.
     */
    public function isFailed(): bool
    {
        return $this->status === self::FAILED;
    }

    /**
     * Determine whether notification has been read.
     */
    public function isRead(): bool
    {
        return $this->status === self::READ;
    }

    /**
     * Determine whether notification is waiting to be sent.
     */
    public function isPending(): bool
    {
        return $this->status === self::PENDING;
    }

    /**
     * Determine whether notification is an email.
     */
    public function isEmail(): bool
    {
        return $this->channel === 'Email';
    }

    /**
     * Determine whether notification is an in-app notification.
     */
    public function isInApp(): bool
    {
        return $this->channel === 'In-App';
    }
}