<?php

declare(strict_types=1);

namespace App\Models;

use App\Enums\NotificationChannel;
use App\Enums\NotificationStatus;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * ==========================================================================
 * INFRASTRUCTURE MODEL
 * ==========================================================================
 *
 * Notification Model
 * ==========================================================================
 *
 * Represents one notification generated by the platform.
 *
 * Notifications are created automatically by the Workflow Engine
 * whenever an event requires informing a User.
 *
 * This model stores notification metadata only.
 * Delivery is handled later by NotificationService.
 *
 * --------------------------------------------------------------------------
 * Responsibilities
 * --------------------------------------------------------------------------
 * • Belongs to one Request.
 * • Targets one User.
 * • Supports Email notifications.
 * • Supports In-App notifications.
 * • Supports reminders.
 * • Supports escalation.
 * • Records delivery status.
 *
 * --------------------------------------------------------------------------
 * Business Rules
 * --------------------------------------------------------------------------
 * BR-43 Notifications are generated automatically.
 * BR-44 Email and In-App supported.
 * BR-45 Reminder notifications.
 * BR-46 Escalation after timeout.
 * BR-47 Delivery failures logged.
 *
 * --------------------------------------------------------------------------
 * Module
 * --------------------------------------------------------------------------
 * Infrastructure
 * ==========================================================================
 */

class Notification extends Model
{
    use HasFactory;

    /*-------------------------------------------------------------------------
    | Mass Assignment
    |------------------------------------------------------------------------*/

    protected $fillable = [

        'request_id',

        'recipient_id',

        'title',

        'message',

        'channel',

        'status',

        'sent_at',

        'read_at',

        'failure_reason',

        'attempt_count',

        'last_attempt_at',

    ];

    /*-------------------------------------------------------------------------
    | Attribute Casting
    |------------------------------------------------------------------------*/

    protected function casts(): array
    {
        return [

            'channel' => NotificationChannel::class,

            'status' => NotificationStatus::class,

            'sent_at' => 'datetime',

            'last_attempt_at' => 'datetime',

            'attempt_count' => 'integer',

            'read_at' => 'datetime',

            'created_at' => 'datetime',

            'updated_at' => 'datetime',

        ];
    }

    /*-------------------------------------------------------------------------
    | Runtime Relationships
    |------------------------------------------------------------------------*/

    /**
     * Related Request.
     */
    public function request(): BelongsTo
    {
        return $this->belongsTo(Request::class);
    }

    /*-------------------------------------------------------------------------
    | Organization Relationships
    |------------------------------------------------------------------------*/

    /**
     * User receiving the notification.
     */
    public function recipient(): BelongsTo
    {
        return $this->belongsTo(User::class, 'recipient_id');
    }

    /*-------------------------------------------------------------------------
    | Query Scopes
    |------------------------------------------------------------------------*/

    /**
     * Pending notifications.
     */
    public function scopePending(Builder $query): Builder
    {
        return $query->where('status', NotificationStatus::Pending);
    }

    /**
     * Successfully sent notifications.
     */
    public function scopeSent(Builder $query): Builder
    {
        return $query->where('status', NotificationStatus::Sent);
    }

    /**
     * Failed notifications.
     */
    public function scopeFailed(Builder $query): Builder
    {
        return $query->where('status', NotificationStatus::Failed);
    }

    /**
     * Read notifications.
     */
    public function scopeRead(Builder $query): Builder
    {
        return $query->where('status', NotificationStatus::Read);
    }

    /*-------------------------------------------------------------------------
    | Helper Methods
    |------------------------------------------------------------------------*/

    /**
     * Determine whether notification was sent.
     */
    public function isSent(): bool
    {
        return $this->status === NotificationStatus::Sent;
    }

    /**
     * Determine whether notification failed.
     */
    public function isFailed(): bool
    {
        return $this->status === NotificationStatus::Failed;
    }

    /**
     * Determine whether notification has been read.
     */
    public function isRead(): bool
    {
        return $this->status === NotificationStatus::Read;
    }

    /**
     * Determine whether notification is waiting to be sent.
     */
    public function isPending(): bool
    {
        return $this->status === NotificationStatus::Pending;
    }

    /**
     * Determine whether notification is an email.
     */
    public function isEmail(): bool
    {
        return $this->channel === NotificationChannel::Email;
    }

    /**
     * Determine whether notification is an in-app notification.
     */
    public function isInApp(): bool
    {
        return $this->channel === NotificationChannel::InApp;
    }

    /**
     * Determine whether this notification has used up its retry budget
     * (BR-47). Reads config('workflow.notification_retry_attempts') -
     * Etape 2 - so the limit can be tuned without a code change.
     */
    public function hasExceededRetryLimit(): bool
    {
        return $this->attempt_count >= (int) config('workflow.notification_retry_attempts', 3);
    }
}